CodeTestTotal/Controllers/ClientController.cs
using CodeTestTotal.Interfaces;
using CodeTestTotal.Models;
using CodeTestTotal.Services;
using CodeTestTotal.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CodeTestTotal.Controllers
{
    public class ClientController : Controller
    {
        private IPetService _IPetService;
        private IClientService _IClientService;
        private readonly IUserService _IUserService;
        private UserManager<Usuario> _UserManager;
        public ClientController(IPetService IPetService, IClientService IClientService, IUserService iUserService, UserManager<Usuario> UserManager)
        {
            _IPetService = IPetService;
            _IClientService = IClientService;
            _IUserService = iUserService;
            _UserManager = UserManager;
        }

        public async Task<IActionResult> Index()
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Cliente");

            if (roles == true)
            {

                var client = _IClientService.GetClient(userID);

                if (client == null)
                {
                    return RedirectToAction("Login", "User");
                }

                var mascotas = _IPetService.GetClientPets(client.ClienteID);
                return View(mascotas);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public async Task<ActionResult> ListClientPets()
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Vendedor");

            if (roles == true)
            {
                List<ListClientPetsViewModel> Model = new List<ListClientPetsViewModel>();
                /*Get All clients*/
                var Clients = _IClientService.GetAllClients();


                foreach (var Client in Clients)
                {
                    ListClientPetsViewModel oItem = new ListClientPetsViewModel();

                    oItem.clientID = Client.ClienteID;
                    oItem.clientName = Client.ClienteNombre;

                    var petsClient = _IPetService.GetClientPets(Client.ClienteID);
                    oItem.pets = petsClient;

                    oItem.cantOrder = 5;

                    Model.Add(oItem);
                }

                return View(Model);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }

        public async Task<ActionResult> _ListPets(int clientID)
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Vendedor");

            if (roles == true)
            {
                var model = _IPetService.GetClientPets(clientID);
                return PartialView(model);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

CodeTestTotal/Controllers/OrderController.cs
using CodeTestTotal.Interfaces;
using CodeTestTotal.Models;
using CodeTestTotal.Services;
using CodeTestTotal.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using System.Collections.Concurrent;

namespace CodeTestTotal.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrdenService _IOrdenService;
        private readonly IPetService _IPetService;
        private readonly IClientService _IClientService;
        private readonly IUserService _IUserService;
        private UserManager<Usuario> _UserManager;
        private ISellerService _ISellerService;
        public OrderController(IOrdenService IOrdenService, IPetService IPetService, IClientService IClientService, IUserService iUserService, UserManager<Usuario> UserManager, ISellerService ISellerService)
        {
            _IOrdenService = IOrdenService;
            _IPetService = IPetService;
            _IClientService = IClientService;
            _IUserService = iUserService;
            _UserManager = UserManager;
            _ISellerService = ISellerService;
        }

        public async Task<ActionResult> NewOrder(int mascotaID, string nameMascota)
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Cliente");

            if (roles == true)
            {
                /*Logic for pets combo*/
                /*Para gatos:
                    ● Cantidad de alimento igual a 0.5 veces su peso.
                    ● Un complemento dietario si el gato tiene más de 5 años.
                    ● Un complemento dietario extra si el gato está castrado.
                Para perros:
                    ● Cantidad de alimento igual a 0.8 veces su peso.
                    ● Un complemento dietario por cada 3 años edad.
                    ● Un complemento dietario extra si el perro está castrado y tiene más de 5 años.*/

                var pet = _IPetService.GetPetByID(mascotaID);

                /*model*/
                NewOrdenViewModel Model = new NewOrdenViewModel();
                double alimento = 0;
                int complementoDietario = 0;
                int complementoDietarioExtra = 0;

                if (pet.MascotaTipo == "G")
                {
                    alimento = pet.MascotaPeso * 0.5;
                    if (pet.MascotaEdad > 5)
                        complementoDietario = 1;

                    if (pet.MascotaCastrado == true)
                        complementoDietarioExtra = 1;

                }
                else
                {
                    alimento = pet.MascotaPeso * 0.8;

                    int v = pet.MascotaEdad / 3;
                    complementoDietario = 1 * int.Parse(v.ToString());

                    if (pet.MascotaCastrado == true && pet.MascotaEdad > 5)
                        complementoDietarioExtra = 1;
                }

                Model.CantidadAlimiento = alimento;
                Model.CantComplementoAlimientoEdad = complementoDietario;
                Model.CantComplementoAlimientoCastrado = complementoDietarioExtra;
                Model.MascotaID = mascotaID;
                Model.MascotaNombre = nameMascota;
                Model.MascotaPeso = pet.MascotaPeso;
                Model.MascotaEdad = pet.MascotaEdad;
                Model.MascotaCastrado = pet.MascotaCastrado;

                return PartialView(Model);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }

        [HttpPost]
        public async Task<ActionResult> NewOrder(NewOrdenViewModel oNewOrdenViewModel)
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Cliente");

            if (roles == true)
            {
                if (!ModelState.IsValid)
                {
                    return View(oNewOrdenViewModel);
                }

                var result = await _IOrdenService.AddNewOrder(oNewOrdenViewModel);

                if (result)
                {
                    return RedirectToAction("Index", "Client");
                }

                ModelState.AddModelError("", "Errores al intentar agregar la orden");
                return View(oNewOrdenViewModel);

            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public async Task<ActionResult> MyOrders(int mascotaID, string nameMascota, string mascotaTipo)
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Cliente");

            if (roles == true)
            {
                List<MyOrdersViewModel> Model = new List<MyOrdersViewModel>();

                var orders = await _IOrdenService.GetPetsOrders(mascotaID);

                string foodImage = "";
                if (mascotaTipo == "P")
                    foodImage = "ComidaPerro.png";
                else
                    foodImage = "ComidaGato.png";

                foreach (var order in orders)
                {
                    MyOrdersViewModel itemModel = new MyOrdersViewModel();
                    itemModel.PetName = nameMascota;

                    itemModel.PetFoodImage = foodImage;

                    if (order.PedidoVendedorID != null)
                    {
                        itemModel.OrderMessage = $"El pedido para {nameMascota} realizado a las {order.PedidoFecha} fue despachado con éxito a las {order.PedidoFechaDespachado} por el vendedor {order.PedidoVendedorNombre}";
                        itemModel.PetOrderProgressImage = "Despachado.png";
                    }
                    else
                    {
                        itemModel.OrderMessage = $"El pedido para {nameMascota} realizado a las {order.PedidoFecha} no fue despachado";
                        itemModel.PetOrderProgressImage = "NoDespachado.png";
                    }
                    Model.Add(itemModel);
                }

                return PartialView(Model);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }

        public async Task<ActionResult> ListOrders(int vendedorID = 0, int ClientID = 0)
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Vendedor");

            if (roles == true)
            {
                /*Get order history*/
                var orders = await _IOrdenService.GetAllOrders();

                List<ListOrdersViewModel> Model = new List<ListOrdersViewModel>();

                foreach (var oItem in orders)
                {
                    //For each order... we get the pet and client
                    ListOrdersViewModel oListOrdersViewModel = new ListOrdersViewModel();

                    var oPet = _IPetService.GetPetByID(oItem.PedidoMascotaID);
                    var client = _IClientService.GetClientByID(oPet.MascotaClientID);

                    oListOrdersViewModel.PedidoID = oItem.PedidoID;
                    oListOrdersViewModel.MascotaNombre = oPet.MascotaNombre;
                    oListOrdersViewModel.ClienteNombre = client.ClienteNombre;
                    oListOrdersViewModel.ClienteID = client.ClienteID;
                    oListOrdersViewModel.PedidoFecha = oItem.PedidoFecha;
                    oListOrdersViewModel.PedidoFechaDespachado = oItem.PedidoFechaDespachado;
                    oListOrdersViewModel.PedidoVendedorID = oItem.PedidoVendedorID;
                    oListOrdersViewModel.PedidoVendedorNombre = oItem.PedidoVendedorNombre;

                    Model.Add(oListOrdersViewModel);
                }

                if (vendedorID != 0)
                    Model = Model.Where(x => x.PedidoVendedorID == vendedorID).ToList();

                if (ClientID != 0)
                    Model = Model.Where(x => x.ClienteID == ClientID).ToList();

                return View(Model);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }

        public async Task<ActionResult> MarkAsDespachado([FromBody] int PedidoID)
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Vendedor");

            if (roles == true)
            {
                if (PedidoID <= 0)
                {
                    return View();
                }
                var vendedor = await _ISellerService.GetSellerByUserID(userID);

                var result = await _IOrdenService.MaskAsDespachado(PedidoID, vendedor.VendedorID);

                if (result)
                    return await ListOrders();

                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }

    }
}

CodeTestTotal/Controllers/PetController.cs
using CodeTestTotal.Interfaces;
using CodeTestTotal.Models;
using CodeTestTotal.Services;
using CodeTestTotal.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CodeTestTotal.Controllers
{
    public class PetController : Controller
    {
        private readonly IPetService _IPetService;
        private readonly IUserService _IUserService;
        private UserManager<Usuario> _UserManager;
        private IClientService _IClientService;
        public PetController(IPetService IPetService, IUserService iUserService, UserManager<Usuario> UserManager, IClientService IClientService)
        {
            _IPetService = IPetService;
            _IUserService = iUserService;
            _UserManager = UserManager;
            _IClientService = IClientService;
        }
        public async Task<IActionResult> AddPetAsync()
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Cliente");

            if (roles == true)
            {
                List<SelectListItem> lstTipoMascota = new List<SelectListItem>();
                lstTipoMascota.Add(new SelectListItem() { Text = "Perro", Value = "P" });
                lstTipoMascota.Add(new SelectListItem() { Text = "Gato", Value = "G" });

                List<SelectListItem> lstCastrado = new List<SelectListItem>();
                lstCastrado.Add(new SelectListItem() { Text = "Si", Value = "Si" });
                lstCastrado.Add(new SelectListItem() { Text = "No", Value = "No" });

                ViewBag.OpcionesTipoMascota = lstTipoMascota;
                ViewBag.OpcionesCastrado = lstCastrado;
                return PartialView();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }

        [HttpPost]
        public async Task<ActionResult> AddPetAsync(AddPetViewModel NewPet)
        {
            var claims = User.Claims.ToList();
            var userID = int.Parse(claims[0].Value);

            var user = await _IUserService.GetUserById(userID);
            var roles = await _UserManager.IsInRoleAsync(user, "Cliente");

            if (roles == true)
            {
                if (!ModelState.IsValid)
                {
                    List<SelectListItem> lstTipoMascota = new List<SelectListItem>();
                    lstTipoMascota.Add(new SelectListItem() { Text = "Perro", Value = "P" });
                    lstTipoMascota.Add(new SelectListItem() { Text = "Gato", Value = "G" });

                    List<SelectListItem> lstCastrado = new List<SelectListItem>();
                    lstCastrado.Add(new SelectListItem() { Text = "Si", Value = "Si" });
                    lstCastrado.Add(new SelectListItem() { Text = "No", Value = "No" });

                    ViewBag.OpcionesTipoMascota = lstTipoMascota;
                    ViewBag.OpcionesCastrado = lstCastrado;
                    return View(NewPet);
                }

                var client = _IClientService.GetClient(userID);

                if(client == null)
                {
                    ModelState.AddModelError(string.Empty, "El usuario no tiene relacionado un cliente, no podrá realizar ésta operación");
                    return View(NewPet);
                }

                if (await _IPetService.AddNewPetAsync(NewPet, client.ClienteID))
                {
                    return RedirectToAction("Index", "Client");
                }

                ModelState.AddModelError(string.Empty, "Error al generar mascota");
                return View(NewPet);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }

        }
    }
}

CodeTestTotal/Views/Client/Index.cshtml
@model List<Mascota>
@{
    ViewData["Title"] = "Hola";
}
<a class="d-flex btnInfo btn btn-success"  onclick="AddNewPet()">
    Agregar mascota
</a>
<div id="id01" class="modal">

</div>

<section class="misMascotas">

    @foreach (Mascota item in Model)
    {
        <article class="Mascota">
            <h2>@item.MascotaNombre</h2>
            <div class="Mascota_imagenes">

                @if (@item.MascotaImg != null)
                {
                    <img src="/Images/@item.MascotaImg" alt="@item.MascotaNombre" title="@item.MascotaNombre" class="Mascota_foto">
                }
                else
                {

                    @if (@item.MascotaTipo == "P")
                    {
                        <img src="/Images/perroDefault.png" alt="@item.MascotaNombre" title="@item.MascotaNombre" class="Mascota_foto">
                    }
                    else
                    {
                        <img src="/Images/GatoDefault.png" alt="@item.MascotaNombre" title="@item.MascotaNombre" class="Mascota_foto">
                    }

                }

                @if (item.MascotaTipo == "P")
                {
                    <img src="/Images/perro.png" class="mascota_tipo">
                }
                else
                {
                    <img src="/Images/gato.png" class="mascota_tipo">
                }
            </div>
            <button class="btnInfo" onclick="AddNewOrder(@item.MascotaID, '@item.MascotaNombre')" id="btnOpenModalNewOrder">Pedido</button>
            <button class="btnInfo" onclick="ShowOrders(@item.MascotaID, '@item.MascotaNombre', '@item.MascotaTipo' )" id="btnOpenModalNewOrder">Historial</button>
        </article>
    }

</section>


<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script>
    var url = '@Url.Action("NewOrder","Order")';
    var urlOrders = '@Url.Action("MyOrders","Order")';
    var urlAddPet = '@Url.Action("AddPet","Pet")';

    function AddNewOrder(MascotaID, MascotaNombre) {
        document.getElementById('id01').style.display = 'block'

        $.get(url, { MascotaID: MascotaID, MascotaNombre: MascotaNombre }, llegadaDatos);
    }

    function ShowOrders(MascotaID, MascotaNombre, MascotaTipo) {
        document.getElementById('id01').style.display = 'block'

        $.get(urlOrders, { mascotaID: MascotaID, nameMascota: MascotaNombre, mascotaTipo: MascotaTipo }, llegadaDatos);
    }

    function AddNewPet() {
        document.getElementById('id01').style.display = 'block'

        $.get(urlAddPet, {}, llegadaDatos);

    }

    
    function llegadaDatos(datos) {
        document.getElementById("id01").innerHTML = datos;
    }

    // Get the modal
    var modal = document.getElementById('id01');

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

CodeTestTotal/Views/Client/ListClientPets.cshtml
@using CodeTestTotal.ViewModel;
@model List<ListClientPetsViewModel>


<!-- The Modal (contains the Sign Up form) -->
<div id="id01" class="modal">

    <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">times;</span>
</div>
@*<partial name="_ListPets"></partial>*@

<section class="ListClients">

    @foreach (var a in Model)
    {
        <article class="card">
            <img src="/Images/img_avatar.png" alt="@a.clientName" style="width:100%">
            <div class="container">
                <h4 class="clientName"><b>@a.clientName</b></h4>
                <div class="buttonsContainer">

                    <a class="button Tarjeta-btnInfo" asp-controller="Order" asp-action="ListOrders" asp-route-ClientID="@a.clientID">Pedidos</a>
                    <input type="hidden" asp-for="@a.clientID">
                    <button class="button info" onclick="ShowContent(@a.clientID)" id="search">Mascotas(@a.pets.Count)</button>
                </div>
            </div>
        </article>
    }
</section>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script>
    var url = '@Url.Action("_ListPets","Client")';

    function ShowContent(id) {
        console.log(id)
        document.getElementById('id01').style.display = 'block'

        $('#id01').load(url, { clientID: id });
    }


    // Get the modal
    var modal = document.getElementById('id01');

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

CodeTestTotal/Views/Client/_ListPets.cshtml
@model List<Mascota>

<section class="ClientPets">
    @if(Model.Count > 0)
    {
        
    @foreach (var a in Model)
    {
        <article class="ClientPetsItem">
            <div class="imgDiv">
                @*<img src="/Images/@a.MascotaImg" class="petImg">*@

                    @if (@a.MascotaImg != null)
                    {
                        <img src="/Images/@a.MascotaImg" alt="@a.MascotaNombre" title="@a.MascotaNombre" class="petImg">
                    }
                    else
                    {

                        @if (@a.MascotaTipo == "P")
                        {
                            <img src="/Images/perroDefault.png" alt="@a.MascotaNombre" title="@a.MascotaNombre" class="petImg">
                        }
                        else
                        {
                            <img src="/Images/GatoDefault.png" alt="@a.MascotaNombre" title="@a.MascotaNombre" class="petImg">
                        }

                    }

                <p>@a.MascotaNombre</p>
            </div>

            <div class="petData">
                <p>Edad: @a.MascotaEdad años</p>
                <p>Tipo: @a.MascotaTipo</p>
                <p>Peso: @a.MascotaPeso kg</p>
                <p>Castrado: @a.MascotaCastrado</p>
            </div>

            </article>
        }

    }
    else
    {
     <p>No tiene mascotas</p>   
    }
</section>